### ISSUE TITLE
Check what starts with camel - is it all needed?

### ISSUE THREAD

**Issue by andrewharmellaw** [andrewharmellaw/camel-boot#16]
Turn off things we don't need, excluding camel config and code if necessary.

**Comment by santosh2020** [comment]
i didn't found any transitive dependency to be excluded from camel dependencies. All are needed.
Below is the gradle dependency tree structure for camel jars.

org.apache.camel:camel-spring-boot:2.16.1  
|    --- org.apache.camel:camel-spring:2.16.1
|         +--- org.apache.camel:camel-core:2.16.1
|         |    +--- org.slf4j:slf4j-api:1.6.6 -> 1.7.13
|         |    +--- com.sun.xml.bind:jaxb-core:2.2.11
|         |    --- com.sun.xml.bind:jaxb-impl:2.2.11
|         --- org.springframework:spring-context:4.1.8.RELEASE -> 4.2.4.RELEASE
|              +--- org.springframework:spring-beans:4.2.4.RELEASE
|              |    --- org.springframework:spring-core:4.2.4.RELEASE
|              +--- org.springframework:spring-core:4.2.4.RELEASE
|              --- org.springframework:spring-expression:4.2.4.RELEASE
|                   --- org.springframework:spring-core:4.2.4.RELEASE
+--- org.apache.camel:camel-netty4-http:2.16.1
|    --- org.apache.camel:camel-netty4:2.16.1
|         +--- org.apache.camel:camel-core:2.16.1 (_)
|         +--- io.netty:netty-all:4.0.33.Final
|         --- commons-pool:commons-pool:1.6
+--- org.apache.camel:camel-jackson:2.16.1
|    +--- org.apache.camel:camel-core:2.16.1 (_)
|    +--- com.fasterxml.jackson.core:jackson-databind:2.6.3 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.0 -> 2.6.4
|    |    --- com.fasterxml.jackson.core:jackson-core:2.6.4
|    --- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.6.3 -> 2.6.4
|         +--- com.fasterxml.jackson.core:jackson-core:2.6.4
|         --- com.fasterxml.jackson.core:jackson-databind:2.6.4 (_)
+--- org.apache.camel:camel-swagger-java:2.16.1
|    +--- org.apache.camel:camel-core:2.16.1 (_)
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.3 -> 2.6.4
|    +--- com.fasterxml.jackson.core:jackson-databind:2.6.3 -> 2.6.4 (_)
|    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.6.3 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.0 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.6.4 (_)
|    |    --- joda-time:joda-time:2.2 -> 2.8.2
|    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.6.3 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.6.4
|    |    --- org.yaml:snakeyaml:1.15 -> 1.16
|    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.6.3 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.6.0 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.6.4 (_)
|    |    +--- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.6.4 (_)
|    |    --- org.codehaus.woodstox:stax2-api:3.1.4
|    +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.6.3
|    |    +--- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:2.6.3
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.6.3 -> 2.6.4
|    |    |    --- com.fasterxml.jackson.core:jackson-databind:2.6.3 -> 2.6.4 (_)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.6.3 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.6.3 -> 2.6.4 (_)
|    |    --- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.6.3 -> 2.6.4 (_)
|    +--- com.google.guava:guava:18.0
|    +--- org.apache.commons:commons-lang3:3.4
|    +--- io.swagger:swagger-core:1.5.4
|    |    +--- org.apache.commons:commons-lang3:3.2.1 -> 3.4
|    |    +--- org.slf4j:slf4j-api:1.6.3 -> 1.7.13
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.5 -> 2.6.4
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.4.5 -> 2.6.4 (_)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-joda:2.4.5 -> 2.6.4 (_)
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.4.5 -> 2.6.4 (_)
|    |    +--- io.swagger:swagger-models:1.5.4
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.4.5 -> 2.6.4
|    |    |    +--- org.slf4j:slf4j-api:1.6.3 -> 1.7.13
|    |    |    --- io.swagger:swagger-annotations:1.5.4
|    |    +--- com.google.guava:guava:18.0
|    |    --- javax.validation:validation-api:1.1.0.Final
|    +--- io.swagger:swagger-annotations:1.5.4
|    --- io.swagger:swagger-jaxrs:1.5.4
|         +--- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.4.5 -> 2.6.4 (_)
|         +--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.4.5 -> 2.6.4 (_)
|         +--- io.swagger:swagger-core:1.5.4 (_)
|         +--- javax.ws.rs:jsr311-api:1.1.1
|         +--- org.reflections:reflections:0.9.10
|         |    +--- com.google.guava:guava:18.0
|         |    +--- org.javassist:javassist:3.18.2-GA -> 3.18.1-GA
|         |    --- com.google.code.findbugs:annotations:2.0.1
|         +--- com.google.guava:guava:18.0
|         --- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:2.4.5 -> 2.6.3 (_)
+--- org.apache.camel:camel-cxf:2.16.1
|    +--- org.apache.camel:camel-core:2.16.1 (_)
|    +--- org.apache.camel:camel-spring:2.16.1 (_)
|    +--- org.apache.camel:camel-cxf-transport:2.16.1
|    |    +--- org.apache.camel:camel-core:2.16.1 (_)
|    |    +--- org.apache.cxf:cxf-rt-bindings-soap:3.1.4
|    |    |    +--- org.apache.cxf:cxf-core:3.1.4
|    |    |    |    +--- org.codehaus.woodstox:woodstox-core-asl:4.4.1
|    |    |    |    |    --- org.codehaus.woodstox:stax2-api:3.1.4
|    |    |    |    --- org.apache.ws.xmlschema:xmlschema-core:2.2.1
|    |    |    +--- org.apache.cxf:cxf-rt-wsdl:3.1.4
|    |    |    |    +--- org.apache.cxf:cxf-core:3.1.4 (_)
|    |    |    |    +--- wsdl4j:wsdl4j:1.6.3
|    |    |    |    --- org.ow2.asm:asm:5.0.4
|    |    |    --- org.apache.cxf:cxf-rt-databinding-jaxb:3.1.4
|    |    |         +--- org.apache.cxf:cxf-core:3.1.4 (_)
|    |    |         +--- org.apache.cxf:cxf-rt-wsdl:3.1.4 (_)
|    |    |         +--- com.sun.xml.bind:jaxb-impl:2.2.11
|    |    |         --- com.sun.xml.bind:jaxb-core:2.2.11
|    |    --- org.springframework:spring-beans:4.1.8.RELEASE -> 4.2.4.RELEASE (_)
|    +--- org.springframework:spring-core:4.1.8.RELEASE -> 4.2.4.RELEASE
|    +--- org.springframework:spring-beans:4.1.8.RELEASE -> 4.2.4.RELEASE (_)
|    +--- org.springframework:spring-context:4.1.8.RELEASE -> 4.2.4.RELEASE (_)
|    --- org.apache.cxf:cxf-rt-bindings-soap:3.1.4 (_)
