### ISSUE TITLE
Git Cleanup

### ISSUE THREAD

**Issue by nikhilvibhav** [andrewharmellaw/camel-boot#3]
loads of stuff is checked in that shouldn't be there, binaries etc.

**Comment by andrewharmellaw** [comment]
You're right @nikhilvibhav - the .gitignore you're aiming for is the same as this one: https://github.com/andrewharmellaw/codahale-metrics-filters/blob/master/.gitignore 

You might also want to ignore files which Eclipse and Netbeans add, but thats not essential.

**Comment by nikhilvibhav** [comment]
Fixed in pull request #14
